// Copyright 2023 QMK
#include "keymap_us_international.h"
#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
     /*
      * ┌───┬───┬───┬───┬───┬───┐       ┌───┬───┬───┬───┬───┬───┐
      * │Esc│ ' │ , │ . │ P │ Y │       │ F │ G │ C │ R │ L │ / │
      * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
      * │Tab│ A │ O │ E │ U │ I │       │ D │ H │ T │ N │ S │ - │
      * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
      * │ \ │ ; │ Q │ J │ K │ X │       │ B │ M │ W │ V │ Z │ \ │
      * └───┴───┴───┴───┴───┴───┘       └───┴───┴───┴───┴───┴───┘
      *               ┌───┐                   ┌───┐
      *               │Up ├───┐           ┌───┤Up │
      *               └───┤Low├───┐   ┌───┤Low├───┘
      *                   └───┤Spc│   │Ent├───┘
      *                       └───┘   └───┘
      */
    [0] = LAYOUT_split_3x6_3(
        KC_ESC , KC_QOUT, KC_COMM, KC_DOT , KC_P   , KC_Y      , KC_F   , KC_G   , KC_C   , KC_R   , KC_L   , KC_SLSH,
        KC_TAB , KC_A   , KC_O   , KC_E   , KC_U   , KC_I      , KC_D   , KC_H   , KC_T   , KC_N   , KC_S   , KC_MINS,
        KC_BSLS, KC_SCLN, KC_Q   , KC_J   , KC_K   , KC_X      , KC_B   , KC_M   , KC_W   , KC_V   , KC_Z   , KC_BSLS,
                                   MO(2)  , MO(1)  , KC_SPC    , KC_ENT , MO(1)  , MO(2)
    ),
     /*
      * ┌───┬───┬───┬───┬───┬───┐       ┌───┬───┬───┬───┬───┬───┐
      * │Esc│ ' │ , │ . │   │   │       │ = │ + │ * │ ^ │ L │ / │
      * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
      * │Tab│ Å │ Ø │ Æ │ ; │   │       │ ! │ ( │ ) │ % │ $ │ - │
      * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
      * │ \ │ ; │   │   │   │   │       │ ` │ [ │ ] │ @ │ # │ \ │
      * └───┴───┴───┴───┴───┴───┘       └───┴───┴───┴───┴───┴───┘
      *               ┌───┐                   ┌───┐
      *               │___├───┐           ┌───┤___│
      *               └───┤___├───┐   ┌───┤___├───┘
      *                   └───┤Del│   │Bsp├───┘
      *                       └───┘   └───┘
      */
    [1] = LAYOUT_split_3x6_3(
        KC_ESC , KC_QUOT, KC_COMM, KC_DOT , XXXXXXX, XXXXXXX   , KC_EQL , KC_PLUS, KC_ASTR, KC_CIRC, XXXXXXX, KC_SLSH,
        KC_TAB , US_ARNG, US_OSTR, US_AE  , KC_SCLN, XXXXXXX   , KC_EXLM, KC_LPRN, KC_RPRN, KC_PERC, KC_DLR , KC_MINS,
        KC_BSLS, KC_SCLN, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX   , KC_GRV , KC_LBRC, KC_RBRC, KC_AT  , KC_HASH, KC_BSLS,
                                   _______, _______, KC_DEL    , KC_BSPC, _______, _______
    ),
     /*
      * ┌───┬───┬───┬───┬───┬───┐       ┌───┬───┬───┬───┬───┬───┐
      * │Esc│   │   │UP │   │   │       │   │ 7 │ 8 │ 9 │   │   │
      * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
      * │Tab│   │LFT│DN │RGT│   │       │ 0 │ 4 │ 5 │ 6 │ , │   │
      * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
      * │ \ │ ; │   │   │   │   │       │   │ 1 │ 2 │ 3 │   │   │
      * └───┴───┴───┴───┴───┴───┘       └───┴───┴───┴───┴───┴───┘
      *               ┌───┐                   ┌───┐
      *               │___├───┐           ┌───┤___│
      *               └───┤___├───┐   ┌───┤___├───┘
      *                   └───┤Spc│   │Ent├───┘
      *                       └───┘   └───┘
      */
    [2] = LAYOUT_split_3x6_3(
        KC_ESC , XXXXXXX, KC_PGDN, KC_UP  , KC_PGUP, XXXXXXX   , XXXXXXX, KC_7   , KC_8   , KC_9, XXXXXXX, XXXXXXX,
        KC_TAB , XXXXXXX, KC_LEFT, KC_DOWN, KC_RGHT, XXXXXXX   , KC_0   , KC_4   , KC_5   , KC_6, KC_KP_DOT, XXXXXXX,
        KC_LSFT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX   , XXXXXXX, KC_1   , KC_2   , KC_3, XXXXXXX, XXXXXXX,
                                   _______, _______, KC_SPC    , KC_ENT , _______, _______
    ),
    [3] = LAYOUT_split_3x6_3(
        QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX   , XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        RM_TOGG, RM_HUEU, RM_SATU, RM_VALU, XXXXXXX, XXXXXXX   , XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        RM_NEXT, RM_HUED, RM_SATD, RM_VALD, XXXXXXX, XXXXXXX   , XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                   KC_LGUI, _______, KC_SPC    , KC_ENT , _______, KC_RALT
    )
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


// // SPDX-License-Identifier: GPL-2.0-or-later
//
// #include QMK_KEYBOARD_H
//
// const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
//      /*
//       * ┌───┬───┬───┬───┬───┬───┐       ┌───┬───┬───┬───┬───┬───┐
//       * │Tab│ Q │ W │ E │ R │ T │       │ Y │ U │ I │ O │ P │Bsp│
//       * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
//       * │Ctl│ A │ S │ D │ F │ G │       │ H │ J │ K │ L │ ; │ ' │
//       * ├───┼───┼───┼───┼───┼───┤       ├───┼───┼───┼───┼───┼───┤
//       * │Sft│ Z │ X │ C │ V │ B │       │ N │ M │ , │ . │ / │Sft│
//       * └───┴───┴───┴───┴───┴───┘       └───┴───┴───┴───┴───┴───┘
//       *               ┌───┐                   ┌───┐
//       *               │GUI├───┐           ┌───┤Alt│
//       *               └───┤Bsp├───┐   ┌───┤Ent├───┘
//       *                   └───┤   │   │   ├───┘
//       *                       └───┘   └───┘
//       */
//     [0] = LAYOUT_split_3x6_3(
//         KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                               KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC,
//         KC_LCTL, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                               KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
//         KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,                               KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
//                                             KC_LGUI, KC_BSPC, KC_SPC,           KC_SPC,  KC_ENT,  KC_RALT
//     )
// };
